# Generated by Django 4.0.4 on 2022-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_check_count',
            name='file',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
