# Generated by Django 4.0.4 on 2022-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_student_check_count_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_check_count',
            name='date',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
