# Generated by Django 4.0.4 on 2022-06-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_check_count_date_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.teacher'),
        ),
    ]
